/// Semantic icon contract for the Taleweaver Word ribbon.
///
/// The glyphs are emitted by a real icon font generated from vector SVG
/// assets. Consumers can replace the font family and/or resolver without
/// changing editor commands or accessibility labels.
library;

/// Icons supplied by the default Taleweaver Office icon font.
enum TaleweaverEditorIcon {
  bold,
  italic,
  underline,
  undo,
  redo,
  cut,
  copy,
  paste,
  alignLeft,
  alignCenter,
  alignRight,
  alignJustify,
  listBullets,
  listNumbered,
  table,
  image,
  textBox,
  rectangle,
  ellipse,
  line,
  save,
  print,
  find,
}

/// Resolves a semantic command icon into one glyph in a font family.
///
/// Use this with TaleweaverEditorAssets.iconResolver when a host installs a
/// font whose private-use codepoints differ from the package default.
typedef TaleweaverEditorIconResolver = String Function(
  TaleweaverEditorIcon icon,
);

/// Fixed, documented private-use codepoints generated by the tool script.
String taleweaverOfficeIconGlyph(TaleweaverEditorIcon icon) {
  final codepoint = switch (icon) {
    TaleweaverEditorIcon.bold => 0xe900,
    TaleweaverEditorIcon.italic => 0xe901,
    TaleweaverEditorIcon.underline => 0xe902,
    TaleweaverEditorIcon.undo => 0xe903,
    TaleweaverEditorIcon.redo => 0xe904,
    TaleweaverEditorIcon.cut => 0xe905,
    TaleweaverEditorIcon.copy => 0xe906,
    TaleweaverEditorIcon.paste => 0xe907,
    TaleweaverEditorIcon.alignLeft => 0xe908,
    TaleweaverEditorIcon.alignCenter => 0xe909,
    TaleweaverEditorIcon.alignRight => 0xe90a,
    TaleweaverEditorIcon.alignJustify => 0xe90b,
    TaleweaverEditorIcon.listBullets => 0xe90c,
    TaleweaverEditorIcon.listNumbered => 0xe90d,
    TaleweaverEditorIcon.table => 0xe90e,
    TaleweaverEditorIcon.image => 0xe90f,
    TaleweaverEditorIcon.textBox => 0xe910,
    TaleweaverEditorIcon.rectangle => 0xe911,
    TaleweaverEditorIcon.ellipse => 0xe912,
    TaleweaverEditorIcon.line => 0xe913,
    TaleweaverEditorIcon.save => 0xe914,
    TaleweaverEditorIcon.print => 0xe915,
    TaleweaverEditorIcon.find => 0xe916,
  };
  return String.fromCharCode(codepoint);
}
